[build-system]
requires = ["setuptools", "setuptools-scm>8.1"]
build-backend = "setuptools.build_meta"

[project]
name = "enmerkar-underscore"
description = "Implements a underscore extractor for django-babel."
requires-python = ">=3.12"
license = "BSD-3-Clause"
license-files = ["LICENSE"]
authors = [
    {name = "Open edX Project", email = "oscm@openedx.org"},
]
classifiers = [
    "Development Status :: 5 - Production/Stable",
    "Framework :: Django",
    "Framework :: Django :: 4.2",
    "Framework :: Django :: 5.2",
    "Intended Audience :: Developers",
    "Natural Language :: English",
    "Programming Language :: Python",
    "Programming Language :: Python :: 3",
    "Programming Language :: Python :: 3.12",
]
keywords = [
    "enmerkar-underscore",
    "Python",
    "edx",
]

dynamic = ["readme", "version"]

dependencies = [
    "django",
    "babel>=1.3",
]

[project.entry-points."babel.extractors"]
underscore = "enmerkar_underscore:extract"

[project.urls]
Homepage = "https://github.com/openedx/enmerkar-underscore"
Repository = "https://github.com/openedx/enmerkar-underscore"

[dependency-groups]
test-base = [
    "coverage",
    "flake8>=2.0",
    "pytest",
    "pytest-cov>=1.4",
    "sphinx",
]
test = [
    {include-group = "test-base"},
    "Django>=5.2,<5.3",
]
django42 = [
    {include-group = "test-base"},
    "Django>=4.2,<4.3",
]
quality = [
    {include-group = "test"},
    "flake8>=2.0",
]
doc = [
    {include-group = "test"},
    "sphinx",
]
ci = [
    "tox",
    "tox-uv",
]
dev = [
    {include-group = "test"},
    {include-group = "quality"},
    {include-group = "doc"},
    {include-group = "ci"},
]

[tool.setuptools]
include-package-data = true

[tool.setuptools.dynamic]
readme = {file = ["README.rst", "HISTORY.rst"], content-type = "text/x-rst"}

[tool.setuptools.packages.find]
where = ["src"]

[tool.setuptools.package-data]
"*" = [
    "*.rst",
    "LICENSE",
    "COPYING",
]

[tool.semantic_release]
build_command = "pip install build && SETUPTOOLS_SCM_PRETEND_VERSION=$NEW_VERSION python -m build"

[tool.setuptools_scm]
version_scheme = 'only-version'
local_scheme = 'no-local-version'
fallback_version = "0.0.0.dev0"

[tool.uv]
conflicts = [
    [{group = "test"}, {group = "django42"}],
]
constraint-dependencies = [
    "Django<6.0",
    "elasticsearch<7.14.0",
    "social-auth-app-django<6.0.0",
    "social-auth-core<5.0.0",
    "pip<26.2.1",
]

[tool.coverage.run]
source = ["src"]

[tool.edx_lint]
uv_constraints = [
]
