[tox]
envlist = py-django{42,52}, docs, quality
requires = tox-uv>=1

[testenv]
runner = uv-venv-lock-runner
setenv =
    PYTHONPATH = {toxinidir}
dependency_groups =
    django42: django42
    django52: test
allowlist_externals = make
commands =
    make test

[testenv:docs]
runner = uv-venv-lock-runner
dependency_groups = test-base
allowlist_externals = sphinx-build
commands =
    sphinx-build -W -b html docs docs/_build/html

[testenv:quality]
runner = uv-venv-lock-runner
dependency_groups = quality
allowlist_externals = make
commands =
    make lint
